name: Windows Latest Swift CI

on:
  push:
    branches: [development, main]

jobs:

  exec-ci:
    runs-on: windows-latest

    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
            branch: swift-5.6.2-release
            tag: 5.6.2-RELEASE

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Debug Test
        shell: pwsh
        run: swift test -c debug

      - name: Release Test
        shell: pwsh
        run: swift test -c release
